### PR TITLE
Added log file creation option.

### PR DESCRIPTION
**Pull request by Cyb3r-Jak3**
Added argument `--log-file` that if set changes the output of the log to a file rather than stout.
Addtionally, linked option for GitHub action that I created,

### CODE REVIEW

**Comment by svenkreiss** [comment]
Thanks for sending the PR. What is the difference to using tee? Like `html5validator someoptions | tee test.log`?

**Comment by Cyb3r-Jak3** [comment]
In my tests, neither `tee` or `>` worked to generate a log file.  

NFNncn2XsX

**Comment by Cyb3r-Jak3** [comment]
Upon further investigation, using `html5validator option &> log.log` will both show in the terminal and create a log file. 

Up to you if you would rather have log file creation in or out of scope.

**Comment by svenkreiss** [comment]
Thanks for following up. The `&>` seems to be a good solution.

**Pull request closed without merging**
