### PR TITLE
Adding --remove-mustaches using pystache (new feature #23)

### PR DESCRIPTION
**Pull request by Lucas-C**

### CODE REVIEW

**Comment by Lucas-C** [comment]
What do you think of this idea ? :)

**Comment by svenkreiss** [comment]
This sounds like a preprocessor to convert mustache templates to HTML. Its
an interesting idea, but I think this is outside of the scope of
html5validator for now and too specific to mustache.

I could see adding a crawler. That would mean you could serve HTML
(possibly generated from mustache templates) and validate the crawled HTML
using html5validator.

**Comment by Lucas-C** [comment]
I don't get the crawler role here. What transformation would it perform on its input exactly ? And what kind of input would it take ? 

But I understand your point about the separation of concerns & mustache templates beeing too specific.

There are many flavours of HTML templating systems. Just to name a few:
- [Handlebar.js](http://handlebarsjs.com) which is really close to mustache templates
- Meteor [Spacebars](https://guide.meteor.com/blaze.html)
- Angular [Markup templates](https://docs.angularjs.org/api/ng/service/$interpolate)
- [Django templates](https://docs.djangoproject.com/en/1.9/ref/templates/language/)
- [jsrender](https://github.com/borismoore/jsrender) for jQuery
- [Shopify/liquid templates](https://github.com/Shopify/liquid)
- [Jinja2](http://jinja.pocoo.org)
- [ES6 template literals](http://exploringjs.com/es6/ch_template-literals.html)

Certainly there is a need for extensibility here, and there is no reason to support only mustache templates.

However, I do not not really agree that this is clearly out of the scope of a Python lib / CLI HTML validator.
It would be really handy for such tool to have "batteries included", and support the most common templating systems, so that one could easily validate its HTML templates without adding any extra layer. I definitely see that that as a "plus" in term of usability.
I think adding "template plugins" could be the best option here. Mustache templates would be just a start, but they cover many cases in the list above (e.g. Angular & Handlebar share the same syntax with it).

Of course, you may not want your validator to take this direction. It's your call, and I can build another tool or fork `html5validator` to add this support for HTML templates.

**Comment by Lucas-C** [comment]
Any thoughts ?

**Comment by svenkreiss** [comment]
I was thinking more about something like [localcrawl](https://pypi.python.org/pypi/localcrawl). This can crawl a local development server and it processes all the JavaScript with a headless browser. It outputs the generated HTML and works with any template engine. The readme contains an example with a small Mustache template.

Does that work for your use case?

**Comment by Lucas-C** [comment]
I worked around this by implementing mustaches-substitution in my pre-commit hook:
https://github.com/Lucas-C/pre-commit-hooks-html

No, `localcrawl` does not really work the way I want.

Closing this

**Pull request closed without merging**
